"""Pydantic v2 models for the Weekly Planning Overview endpoint (GLC-12).

All models use ConfigDict(from_attributes=True) so model_validate() accepts
both ORM objects and raw dicts (e.g. cache-deserialized payloads).
"""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


# ── Sub-models ────────────────────────────────────────────────────────────────

class WeekMeta(BaseModel):
    """Basic week metadata returned at the top of every planning response."""

    model_config = ConfigDict(from_attributes=True)

    id:            str
    label:         str
    week_start:    str            # YYYY-MM-DD; derived as week_ending − 6 days
    week_ending:   str            # YYYY-MM-DD; canonical week key
    status:        str            # "draft" | "published" | "archived"
    schedule_path: Optional[str] = None  # linked ADP export filename


class NightPlanningSnapshot(BaseModel):
    """Per-night coverage and planning health indicators."""

    model_config = ConfigDict(from_attributes=True)

    night_id:                str
    night_date:              str    # YYYY-MM-DD
    day_name:                str    # "Friday" … "Thursday"
    in_rotation:             bool

    # ── Coverage ──────────────────────────────────────────────────────
    total_slots:             int    # all zone_assignment rows for this night
    filled_slots:            int    # rows where tm_id is not null/empty
    gap_count:               int    # total_slots − filled_slots
    coverage_pct:            float  # filled / target * 100; 0 if target == 0
    target_capacity:         int    # per-day staffing target (operational denominator)

    # ── Zone / RR breakdown ───────────────────────────────────────────
    zone_total:              int = 0
    zone_filled:             int = 0
    rr_total:                int = 0
    rr_filled:               int = 0

    # ── Sweepers ─────────────────────────────────────────────────────
    sweeper_main_filled:     bool = False   # "Sweeper 5/8/HL" assigned
    sweeper_sr_filled:       bool = False   # "Sweeper 9/10/SR" assigned

    # ── Overlaps + overrides ──────────────────────────────────────────
    multi_area_overlap_count: int   # rows from get_night_overlaps()
    override_count:           int   # active slot_assignment overrides
    reoptimize_recommended:   bool  # True when gap_count > 0

    # ── Supervisor note ───────────────────────────────────────────────
    note:                    Optional[str] = None


class WeekMetrics(BaseModel):
    """Aggregated metrics across all in-rotation nights for the week."""

    model_config = ConfigDict(from_attributes=True)

    total_assignments:       int    # sum of filled_slots across all nights
    total_gaps:              int    # sum of gap_count across all nights
    nights_with_gaps:        int    # count of nights where gap_count > 0
    multi_area_overlap_count: int   # total multi-area overlap rows for the week
    active_override_count:   int    # total slot_assignment overrides for the week

    # Fatigue index: avg assignments per TM (rough load indicator).
    # Computed as total_assignments / unique_tm_count; 0.0 when no TMs assigned.
    fatigue_index:           float

    # Alias kept for API stability — equals nights_with_gaps.
    reoptimize_opportunities: int


class PlanningNote(BaseModel):
    """A synthetic planning note derived from data analysis.

    These are generated by PlanningService (not fetched from the annotations
    table) so that the endpoint always returns actionable, human-readable
    summaries without requiring a separate annotation write workflow.
    """

    model_config = ConfigDict(from_attributes=True)

    night_id:   str
    day_name:   str
    note_kind:  str   # "gap" | "override" | "overlap" | "info"
    note_text:  str


class OverrideSummary(BaseModel):
    """Flattened view of one slot_assignment override."""

    model_config = ConfigDict(from_attributes=True)

    night_id:   str
    day_name:   str
    slot_key:   str
    tm_id:      Optional[str] = None
    note:       Optional[str] = None
    created_at: Optional[str] = None


class PlanningLinks(BaseModel):
    """Hyperlink references useful to a planning client."""

    model_config = ConfigDict(from_attributes=True)

    print_week_html: str   # /v1/print/week/{week_id}.html
    print_week_pdf:  str   # /v1/print/week/{week_id}.pdf
    reoptimize:      str   # /v1/engine/week/{week_id}/reoptimize  (Phase 5 GLC-10)


# ── Schedule / trail models ───────────────────────────────────────────────────

class ScheduledTM(BaseModel):
    """One TM in the nightly schedule with their attendance status overlay."""

    model_config = ConfigDict(from_attributes=True)

    tm_id:     str
    tm_name:   str
    status:    str = "present"   # present | late | call_out | no_show
    note:      Optional[str] = None
    break_wave: Optional[int] = None   # 1 | 2 | 3; from break_assignments


class TrailEntry(BaseModel):
    """One entry in the night audit trail (night_audit_log)."""

    model_config = ConfigDict(from_attributes=True)

    night_id:    str
    action_type: str              # assign | clear | lock | unlock | swap | status | engine_run | note
    slot_id:     Optional[str] = None
    zone_label:  Optional[str] = None
    tm_from:     Optional[str] = None
    tm_to:       Optional[str] = None
    detail:      Optional[str] = None
    actor:       str = "supervisor"


# ── Top-level response ────────────────────────────────────────────────────────

class WeeklyPlanningOverviewResponse(BaseModel):
    """Full weekly planning overview — the GLC-12 contract.

    Clients can use this single call to build a pre-shift dashboard showing
    coverage health, gaps, active overrides, and quick-action links.
    """

    model_config = ConfigDict(from_attributes=True)

    week:             WeekMeta
    nights:           list[NightPlanningSnapshot] = Field(default_factory=list)
    metrics:          WeekMetrics
    planning_notes:   list[PlanningNote]          = Field(default_factory=list)
    active_overrides: list[OverrideSummary]        = Field(default_factory=list)
    links:            PlanningLinks
    cached_at:        str   # ISO-8601 UTC timestamp; set by PlanningService
